source("http://www.bioconductor.org/biocLite.R")
setwd("~/cufflinks/10_11_diffout.celegans/")
biocLite("cummeRbund")
install.packages("Rcpp")
install_version("RSQLite", version = "1.1-2", repos = "http://cran.us.r-project.org")
install_version("RSQLite", version = "2.0", repos = "http://cran.us.r-project.org")
install_github("r-dbi/RSQLite")
install.packages("RSQLite")
library(devtools)
library(Rcpp)
library("RSQLite")
library(cummeRbund)
library(reshape2)
library(ggplot2)
library(plyr)
library(fastcluster)
library(rtracklayer)
library(Gviz)
library(BiocGenerics)
cuff_data <- readCufflinks(dbFile = "cuffData.db", gtfFile = "Caenorhabditis_elegans.WBcel235.90.gtf")

csDensity(genes(cuff_data))
csScatter(genes(cuff_data), "10", "11")
csVolcano(genes(cuff_data), "10", "11")
mygene < - getGene(cuff_data, "regucalcin")
expressionBarplot(mygene)
expressionBarplot(isoforms(mygene))



